Repository jupyterlab-contrib/jupyterlab-vim, pull requests merged in 2023-09, with the labels that each got.

#105 Fix `modifyCell` or `modifyEditor` not called after text editor is opened after notebook
  CHANGELOG.md
  src/index.ts
Labels: bug

#108 Update README.md for `main` branch
  CHANGELOG.md
  README.md
Labels: maintenance

#107 Fix search box `Esc` bindings
  schema/plugin.json
  src/codemirrorCommands.ts
Labels: bug

#110 Add settings to enable double duty `Esc` and to disable `Shift-Esc` override in Command mode
  schema/plugin.json
  src/index.ts
Labels: enhancement
