Repository jupyterlab-contrib/jupyterlab-vim, pull requests merged in 2023-08, with the labels that each got.

#93 build: don't require package.json for python import
  jupyterlab_vim/__init__.py
Labels: enhancement, maintenance

#95 Fix for attempting to update editor when there was none
  src/codemirrorCommands.ts
Labels: bug

#97 fix: dev install + lint issues
  .prettierrc
  jupyterlab_vim/__init__.py
  package.json
Labels: maintenance

#99 Fix __init__.py for wheel
  .github/workflows/build.yml
  jupyterlab_vim/__init__.py
Labels: bug

#82 Clear input state if applicable before hopping out of normal mode to jupyter command mode
  src/labCommands.ts
Labels: enhancement

#100 fix: override browser shift-esc in command mode
  schema/plugin.json
Labels: bug
