Repository jupyterlab-contrib/jupyterlab-vim, pull requests merged in 2023-07, with the labels that each got.

#85 Support JupyterLab 4.0
  .eslintrc.js
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .gitignore
  .prettierignore
  .yarnrc.yml
  CHANGELOG.md
  History.md
  MANIFEST.in
  README.md
  RELEASE.md
  binder/environment.yml
  binder/labextensions.txt
  binder/postBuild
  installing.md
  jupyterlab_vim/_version.py
  modify-keybinds.md
  package.json
  pyproject.toml
  schema/plugin.json
  setup.py
  src/codemirrorCommands.ts
  src/index.ts
  src/labCommands.ts
  style/base.css
  style/index.css
  style/index.js
  tsconfig.json
  yarn.lock
Labels: maintenance

#87 maintenance: Release updates
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: maintenance

#91 Remove duplicate binder-on-pr action
  .github/workflows/bind-on-pr.yaml
Labels: maintenance

#90 Add support for vim mode in Text Editor
  package.json
  schema/plugin.json
  src/codemirrorCommands.ts
  src/index.ts
  src/labCommands.ts
  yarn.lock
Labels: enhancement

#92 Fix undo
  src/codemirrorCommands.ts
Labels: bug
