Repository jupyterlab-contrib/jupyterlab-vim, pull requests merged in 2023-10, with the labels that each got.

#114 Correct project name to `jupyterlab-vim`
  pyproject.toml
Labels: maintenance

#121 Delete `installing.md` and mention in README
  README.md
  installing.md
Labels: documentation

#122 Correct license classifier in `pyproject.toml`
  pyproject.toml
Labels: maintenance

#119 Don't render Markdown when attempting to navigate above first cell
  src/codemirrorCommands.ts
  src/index.ts
  src/labCommands.ts
Labels: bug

#116 Clarify settings location
  modify-keybinds.md
Labels: documentation
